language: cpp
sudo: false
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libboost1.55-all-dev
    - libboost-serialization1.55-dev
    - libboost-system1.55-dev
    - libboost-chrono1.55-dev
    - libboost-timer1.55-dev
    - g++-4.8
install:
    - if [[ "${CC}" == "gcc" ]]; then
          export CC=gcc-4.8;
          export CXX=g++-4.8;
      fi
env:
    - BUILD_TYPE="Debug"
    - BUILD_TYPE="Release"
script:
    - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} .
    - make
    - ctest -E gastineau --output-on-failure
notifications:
  email: false
