language: cpp
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-4.8
    - clang-3.8
    - graphviz
    - graphviz-dev
    - texlive
    - gcc-5
    - g++-5
    - curl

env:
  global:
    - secure: "Wv5gHHcF9AKEboPhLPbXEjAJKe/YRT3bpQChPHBmlv4mylCJNAh/satTVmumZItVeNRV/V9mk3ckDGWt6g4X7o9Md/MB1+UmGUCb9AakI288llc90puYWDnSGjgSpTVhB8PfrJa45u9jBLqgPO/S6G5zhPUC4Cru40j7hvUpThaVIiRwj2KlzUwjz/m9YTcxTmBFD+wNr8b6ViNP7BiH6G+RP+fcmd9w9D2pLzCpuBtUpQfZhn+Ar07Nt36weDgpGSzPcpKAJC99Tfi+Bu/NauSYKKdDtbRpBC9z3QRZrNFn5nJ/VFJNWsqpAlCZhHHbO2Ph3YK5SKn/ya37KtrGNYaRIy1QTL6chXeMmluemalIRoF+pkjKv2sQ/Pj8mUx9pbpboHyJivqvM3HpnetJEI6rz+FX14GmpHJn1gNhaHEm0DyubafqE6tfUjo+5mDOK0hoP/dHAEoXkCysL+8tQUWMP0qztjFZrcLhTIoGDH2x04KeqOoZdkRnzIp9tSDIZNFgm0Q/B/4c2r7Wv/N7t6z+LQKFsz9YORMMnADTEI+DjgZIVtjOf0I39T7pjlTZIKDL98bmIs5CKVlj1bNdyMf/97tDi3Xqc9NKrdp404Os3tqBaqMSXAT9VmrTHXPqt809g14m1wlt7zf5BhTMm+WhYP68iqjVXV9hIGBxzj0="
    - secure: "YAFDKbEchL+t/DUaahOX1vAa5ilzq08uln70a7/QHhHJqIazrXA5Pf+pSImydDJpt73Kbd5h1urZs6JXGMKVhPPnSo0aV5PuuiNbLw8sqHA5s3sm2vTgEsSCko2i2nI7SO92+lw7dRJHSO4Rz3QL8aGMS+pR8PMbGD+MuBz0ASCvc9GBMuIkyB0Sbm0v25cCWmi+M+FAj2Adg3IPlr/SgPDnSPxjXauTPrkcnSqoGH9c9A8Jxfk+7ER/Zbo3i1cW4oOb/L5diACjTsbV503onFlqvG3jOngEm4x8KfEwZZGiaOuCYP9n0/xOOVgjf+l+um0bzdt/wt/949f7lJFyVK5bxa4k6JJlIpKhP4bH2QASA2nip3HDbdi7bfMz79CAYyJ5I3F/PHWQ9kH5DK5PrZKdPGqyPDuBoq2W5ERy+3bJzkd1tYjhW/5vjvSiRiILxa6PF43jQ+73nx09td7CtCtd6aWsM1rOtyCfoZpzzCvKWqaVdw3au2fzKZBcuCK8CQT+xQTPNzqrH1/iA80K4M9r1Z9o0YRksYko9i7WlIi8nQc14g0g4namHSPrD/kPhj3/gYErXXNn/GmyqgBQrRfpi0PXl9M9Bcg3YMHT8sqbR3Y1GAxgCOh7+lAq7HwTsxESXQl0ywmmzHsGIvAingTFSauwzotWGYR82IxUDjk="

matrix:
  include:
    - compiler: gcc
      env: BUILD_TYPE="Release"
    - compiler: gcc
      env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="0"
    - compiler: gcc
      env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="1"
    - compiler: gcc
      env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="2"
    - compiler: gcc
      env: BUILD_TYPE="Coverage" SPLIT_TEST_NUM="0"
    - compiler: gcc
      env: BUILD_TYPE="Coverage" SPLIT_TEST_NUM="1"
    - compiler: gcc
      env: BUILD_TYPE="Coverage" SPLIT_TEST_NUM="2"
    - compiler: clang
      env: BUILD_TYPE="Release"
    - compiler: clang
      env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="0"
    - compiler: clang
      env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="1"
    - compiler: clang
      env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="2"
    - compiler: clang
      env: BUILD_TYPE="Python2"
    - compiler: clang
      env: BUILD_TYPE="Python3"
    - compiler: clang
      env: BUILD_TYPE="Tutorial"
    - compiler: gcc
      env: BUILD_TYPE="Doxygen"

install:
    - if [[ "${CC}" == "clang" ]]; then
          export PIRANHA_COMPILER=clang;
          export CC=clang-3.8;
          export CXX=clang++-3.8;
      elif [[ "${CC}" == "gcc" && "${BUILD_TYPE}" == "Coverage" ]]; then
          export PIRANHA_COMPILER=gcc;
          export CC=gcc-5;
          export CXX=g++-5;
          export GCOV_EXECUTABLE=gcov-5;
      else
          export PIRANHA_COMPILER=gcc;
          export CC=gcc-4.8;
          export CXX=g++-4.8;
      fi
script:
    - mkdir build
    - cd build
    - source ../tools/install_msgpack.sh
    - source ../tools/install_travis.sh
notifications:
  email: false
