language: cpp
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    - llvm-toolchain-precise
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libboost1.55-all-dev
    - libboost-serialization1.55-dev
    - libboost-system1.55-dev
    - libboost-chrono1.55-dev
    - libboost-timer1.55-dev
    # This includes both Boost.Python 2 and 3.
    - libboost-python1.55-dev
    - python3-dev
    - python-numpy
    - python3-numpy
    - python-pip
    - g++-4.8
    - clang-3.8

matrix:
  include:
    - compiler: gcc
      env: BUILD_TYPE="Release"
    - compiler: gcc
      env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="0"
    - compiler: gcc
      env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="1"
    - compiler: gcc
      env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="2"
    - compiler: clang
      env: BUILD_TYPE="Release"
    - compiler: clang
      env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="0"
    - compiler: clang
      env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="1"
    - compiler: clang
      env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="2"
    - compiler: clang
      env: BUILD_TYPE="Python2"
    - compiler: clang
      env: BUILD_TYPE="Python3"

install:
    - if [[ "${CC}" == "gcc" ]]; then
          export PIRANHA_COMPILER=gcc;
          export CC=gcc-4.8;
          export CXX=g++-4.8;
      elif [[ "${CC}" == "clang" ]]; then
          export PIRANHA_COMPILER=clang;
          export CC=clang-3.8;
          export CXX=clang++-3.8;
      fi
    # - export BOOST_TEST_LOG_LEVEL="all"
script:
    - mkdir build
    - cd build
    - source ../tools/install_travis.sh
after_success:
    - /home/travis/.local/bin/coveralls --gcov-options '\-lp'
notifications:
  email: false
