language: cpp
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    - llvm-toolchain-precise
    - kubuntu-backports
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libboost1.55-all-dev
    - libboost-serialization1.55-dev
    - libboost-system1.55-dev
    - libboost-chrono1.55-dev
    - libboost-timer1.55-dev
    # This includes both Boost.Python 2 and 3.
    - libboost-python1.55-dev
    - python3-dev
    - python-numpy
    - python3-numpy
    - python-pip
    - g++-4.8
    - clang-3.8
    - doxygen
    - graphviz
    - graphviz-dev
    - cmake
    - texlive

matrix:
  include:
    #- compiler: gcc
      #env: BUILD_TYPE="Release"
    #- compiler: gcc
      #env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="0"
    #- compiler: gcc
      #env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="1"
    #- compiler: gcc
      #env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="2"
    #- compiler: clang
      #env: BUILD_TYPE="Release"
    #- compiler: clang
      #env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="0"
    #- compiler: clang
      #env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="1"
    #- compiler: clang
      #env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="2"
    #- compiler: clang
      #env: BUILD_TYPE="Python2"
    #- compiler: clang
      #env: BUILD_TYPE="Python3"
    #- compiler: clang
      #env: BUILD_TYPE="Tutorial"
    - env: BUILD_TYPE="Doxygen"
      secure: "l8Zz7Ga8e1AWz1xw6VeiqFon/dYeJEkpb/tVF8c3UhB9s56gYxcdov0BoMmbiP6+2BAotajdH0hc5l54Xc28IG1++rC53iTuGTH+MEiNrqsee79jf3t2sm2Y63lleZ7Ylc6WL1rdgCCyl92wmUCW4x3IdbkL3foEVnbM1BP1qYHHoSggwaSFiti0HrryrJf777Yp5sdiYAF2tNrbYUGCJ4pyC5CTijAywLU0SY74Vi+PZmaRp4tVFa/iPE5Pqxyr6n9c4Ty1R9m+MphwhwmvNzhcQIKNlHmTZBQxdNtLIxBwa0F9dqwWIf4a+peZsQJIVOxHWkzfK9TulnYnSozC9FbVoRDiHsd0hofGREb6zXQXeVIN/78TAOXCMlHuFGlnYhWlBe9fB7Rro+A0kyFzXWFBCxP7mtO6r3l+BnbsXdswDdN0Nmrh64eIAuYjLXaTAr9qAwzxubWix9/mKfjSHWKjvgBo7HknRTegwgxwLuEbV7I5Is13g7nKmN7zNrVYqgAMJLYIcjwFPcNAvE5UQoxgLLsc+Zi+3/mdTHStd42xUecKYaCF9sd6rK43eL/jxlnEma6g91hN7JCR6h3e0pkuvznHyTuJezCj/FJvB2IPrji/cKCsKkPBMRKW5LeQH7N8H0iZ8Jx5z8xw9s/J4VyCun+aEJSJ2hl1yuwFoNg="

install:
    - if [[ "${CC}" == "gcc" ]]; then
          export PIRANHA_COMPILER=gcc;
          export CC=gcc-4.8;
          export CXX=g++-4.8;
      elif [[ "${CC}" == "clang" ]]; then
          export PIRANHA_COMPILER=clang;
          export CC=clang-3.8;
          export CXX=clang++-3.8;
      fi
    # - export BOOST_TEST_LOG_LEVEL="all"
script:
    - mkdir build
    - cd build
    - source ../tools/install_travis.sh
#after_success:
    #- if [[ "${BUILD_TYPE}" == "Debug" && "${PIRANHA_COMPILER}" == "clang" ]]; then
          #cd tests;
          #/home/travis/.local/bin/coveralls --gcov-options '\-lp';
      #fi
notifications:
  email: false
