language: cpp
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libboost1.55-all-dev
    - libboost-serialization1.55-dev
    - libboost-system1.55-dev
    - libboost-chrono1.55-dev
    - libboost-timer1.55-dev
    - g++-4.8

matrix:
  include:
    - compiler: gcc
      env: BUILD_TYPE="Release"
    - compiler: clang
      env: BUILD_TYPE="Release"
    - compiler: clang
      env: BUILD_TYPE="Release" CXXFLAGS="-stdlib=libc++"
    - compiler: clang
      env: BUILD_TYPE="Debug"
    - compiler: clang
      env: BUILD_TYPE="Debug" CXXFLAGS="-fsanitize=address"
    - compiler: clang
      env: BUILD_TYPE="Debug" CXXFLAGS="-fsanitize=thread"

install:
    - if [[ "${CC}" == "gcc" ]]; then
          export CC=gcc-4.8;
          export CXX=g++-4.8;
      elif [[ "${CC}" == "clang" ]]; then
          export CXXFLAGS="${CXXFLAGS} -Wno-mismatched-tags";
      fi
script:
    - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} .
    - make
    - if [[ "${BUILD_TYPE}" == "Release" ]]; then
          ctest -E gastineau --output-on-failure;
      elif [[ "${BUILD_TYPE}" == "Debug"  ]]; then
          ctest -E polynomial;
      fi
notifications:
  email: false
