language: cpp
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    - llvm-toolchain-precise
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libboost1.55-all-dev
    - libboost-serialization1.55-dev
    - libboost-system1.55-dev
    - libboost-chrono1.55-dev
    - libboost-timer1.55-dev
    # This includes both Boost.Python 2 and 3.
    - libboost-python1.55-dev
    - python3-dev
    - python-numpy
    - python3-numpy
    - python-pip
    - g++-4.8
    - clang-3.8

matrix:
  include:
    #- compiler: gcc
      #env: BUILD_TYPE="Release"
    #- compiler: gcc
      #env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="0"
    #- compiler: gcc
      #env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="1"
    #- compiler: gcc
      #env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="2"
    #- compiler: clang
      #env: BUILD_TYPE="Release"
    #- compiler: clang
      #env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="0"
    #- compiler: clang
      #env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="1"
    #- compiler: clang
      #env: BUILD_TYPE="Debug" SPLIT_TEST_NUM="2"
    #- compiler: clang
      #env: BUILD_TYPE="Python2"
    - compiler: clang
      env: BUILD_TYPE="Python3"

install:
    - if [[ "${CC}" == "gcc" ]]; then
          export CC=gcc-4.8;
          export CXX=g++-4.8;
      elif [[ "${CC}" == "clang" ]]; then
          export CC=clang-3.8;
          export CXX=clang++-3.8;
      fi
    # - export BOOST_TEST_LOG_LEVEL="all"
script:
    - mkdir build
    - cd build
    - if [[ "${BUILD_TYPE}" == "Debug" ]]; then
          cmake -DCMAKE_BUILD_TYPE=Debug -DPIRANHA_TEST_SPLIT=yes -DPIRANHA_TEST_SPLIT_NUM=${SPLIT_TEST_NUM} ../;
      elif [[ "${BUILD_TYPE}" == "Release" ]]; then
          cmake -DCMAKE_BUILD_TYPE=Release ../;
      elif [[ "${BUILD_TYPE}" == "Python2" ]]; then
          pip install --user mpmath;
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_PYRANHA=yes -DBUILD_TESTS=no -DCMAKE_CXX_FLAGS_DEBUG=-g0 -DCMAKE_CXX_FLAGS=-Os -DCMAKE_INSTALL_PREFIX=/home/travis/.local ../;
          make install;
      elif [[ "${BUILD_TYPE}" == "Python3" ]]; then
          wget "https://bootstrap.pypa.io/get-pip.py"
          python3 get-pip.py --user
          /home/travis/.local/bin/pip install mpmath --user
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_PYRANHA=yes -DBUILD_TESTS=no -DCMAKE_CXX_FLAGS_DEBUG=-g0 -DCMAKE_CXX_FLAGS=-Os -DCMAKE_INSTALL_PREFIX=/home/travis/.local -DBoost_PYTHON_LIBRARY_RELEASE=/usr/lib/x86_64-linux-gnu/libboost_python-py32.so.1.55.0 -DBoost_PYTHON_LIBRARY_DEBUG=/usr/lib/x86_64-linux-gnu/libboost_python-py32.so.1.55.0 -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.2 -DPYTHON_LIBRARY=/usr/lib/libpython3.2mu.so ../;
          make install;
      fi
    - make
    - if [[ "${BUILD_TYPE}" == "Debug" ]]; then
          ctest -E "thread" -V;
      elif [[ "${BUILD_TYPE}" == "Release" ]]; then
          ctest -E "gastineau|perminov" -V;
      elif [[ "${BUILD_TYPE}" == "Python2" ]]; then
          python -c "import pyranha.test; pyranha.test.run_test_suite()";
      elif [[ "${BUILD_TYPE}" == "Python3" ]]; then
          python3 -c "import pyranha.test; pyranha.test.run_test_suite()";
      fi
notifications:
  email: false
